using System.Collections.Generic;

namespace XTPdfMergeApp.Services
{
    /// <summary>Vietnamese for the texts written in XAML: ribbon, panels, settings, dialogs. The key is the English text exactly as it is written.</summary>
    internal static partial class LocVi
    {
        private static void AddChrome(Dictionary<string, string> w)
        {
            void A(string en, string vi) => w[en] = vi;

            // ── ribbon, tabs and the title bar
            A("0 windows", "0 cửa sổ");
            A("About PDF Reader Pro", "Giới thiệu PDF Reader Pro");
            A("Actual size", "Kích thước thật");
            A("Actual size (100%)", "Kích thước thật (100%)");
            A("Add a note at this text", "Thêm ghi chú tại đoạn chữ này");
            A("Add text to this side", "Thêm chữ vào cạnh này");
            A("Align left", "Căn trái");
            A("Align right", "Căn phải");
            A("All open documents", "Mọi tài liệu đang mở");
            A("All open tabs", "Mọi tab đang mở");
            A("Arrow", "Mũi tên");
            A("Arrow head", "Đầu mũi tên");
            A("Bold", "Đậm");
            A("Box border", "Viền khung");
            A("Bring to front", "Đưa lên trên cùng");
            A("Callout", "Chú thích");
            A("Callout: click the point to highlight, then enter the note text", "Chú thích: bấm vào điểm cần chỉ, rồi nhập nội dung");
            A("Capture", "Chụp");
            A("Capture the screen with XT Capture: pick a window, a rectangle, a circle or a polygon. XT Capture also runs from the tray, with its own shortcut.", "Chụp màn hình bằng XT Capture: chọn một cửa sổ, hình chữ nhật, hình tròn hoặc đa giác. XT Capture cũng chạy ở khay hệ thống, có phím tắt riêng.");
            A("Centre", "Giữa");
            A("Close", "Đóng");
            A("Close (Esc)", "Đóng (Esc)");
            A("Close all tabs", "Đóng tất cả tab");
            A("Close file", "Đóng tệp");
            A("Close the panel (Esc)", "Đóng bảng (Esc)");
            A("Closed", "Đã đóng");
            A("Cloud", "Đám mây");
            A("Colour", "Màu");
            A("Command palette: commands, files and pages (Ctrl+K)", "Bảng lệnh: lệnh, tệp và trang (Ctrl+K)");
            A("Comment", "Bình luận");
            A("Compare with another version…", "So sánh với phiên bản khác…");
            A("Continuous scrolling", "Cuộn liên tục");
            A("Copy", "Sao chép");
            A("Copy as path", "Sao chép đường dẫn");
            A("Copy file", "Sao chép tệp");
            A("Delete", "Xóa");
            A("Delete an annotation: click it. Undo restores it.", "Xóa chú thích: bấm vào nó. Hoàn tác sẽ khôi phục.");
            A("Delete the selected page(s)", "Xóa các trang đã chọn");
            A("Document", "Tài liệu");
            A("Drag a rectangle to highlight an area (also works on scanned pages and drawings)", "Kéo một hình chữ nhật để tô sáng vùng (dùng được cả với trang quét và bản vẽ)");
            A("Drag across text to highlight it (needs selectable text)", "Kéo qua chữ để tô sáng (cần trang có chữ chọn được)");
            A("Drag across text to select it, Ctrl+C to copy", "Kéo qua chữ để chọn, Ctrl+C để sao chép");
            A("Drag between two points: the real length at the sheet's scale (Esc clears)", "Kéo giữa hai điểm: đo chiều dài thật theo tỉ lệ bản vẽ (Esc để xóa)");
            A("Drag to change the width", "Kéo để đổi độ rộng");
            A("Drag to move", "Kéo để di chuyển");
            A("Drag to scroll the page (Esc returns to this tool)", "Kéo để cuộn trang (Esc quay về công cụ này)");
            A("Draw a freehand PDF Ink stroke. It remains editable/selectable and is saved with the PDF.", "Vẽ nét tự do (PDF Ink). Nét vẽ vẫn chọn và sửa được, và được lưu cùng PDF.");
            A("Draw an area on a page, find the text inside it on many pages, then replace or delete it.", "Vẽ một vùng trên trang, tìm chữ trong vùng đó trên nhiều trang rồi thay thế hoặc xóa.");
            A("Drawings and scans: select a line, shape or image (or drag an area), then copy it or delete it from the file.", "Bản vẽ và trang quét: chọn một đường, hình hoặc ảnh (hoặc kéo một vùng) rồi sao chép hoặc xóa khỏi tệp.");
            A("Duplicate", "Nhân bản");
            A("Edit", "Chỉnh sửa");
            A("Edit Object ▾", "Sửa đối tượng ▾");
            A("Edit Text", "Sửa chữ");
            A("Edit the real text of the page: click a piece of text, type, then Enter. Only for pages with a text layer. Ctrl+S saves it into the file.", "Sửa chữ thật của trang: bấm vào một đoạn chữ, gõ rồi Enter. Chỉ dùng cho trang có lớp chữ. Ctrl+S để lưu vào tệp.");
            A("Eraser", "Tẩy");
            A("Extract", "Trích xuất");
            A("Extract the selected page(s) to a new file", "Trích các trang đã chọn ra tệp mới");
            A("Fill", "Tô nền");
            A("Fill colour", "Màu nền");
            A("Find", "Tìm");
            A("Find in Area", "Tìm trong vùng");
            A("Find in document (Ctrl+F)", "Tìm trong tài liệu (Ctrl+F)");
            A("Find…", "Tìm…");
            A("Fit page", "Vừa trang");
            A("Fit width", "Vừa chiều rộng");
            A("Font", "Phông chữ");
            A("Font size (pt)", "Cỡ chữ (pt)");
            A("Full screen (F11)", "Toàn màn hình (F11)");
            A("Hand", "Bàn tay");
            A("Highlight", "Tô sáng");
            A("Highlight area", "Tô sáng vùng");
            A("Highlight text", "Tô sáng chữ");
            A("Home: recent files and quick tools", "Trang chủ: tệp gần đây và công cụ nhanh");
            A("Ignore", "Bỏ qua");
            A("Insert", "Chèn");
            A("Insert pages after the current one", "Chèn trang sau trang hiện tại");
            A("Italic", "Nghiêng");
            A("Line", "Đường thẳng");
            A("Line style", "Kiểu nét");
            A("Line width", "Độ dày nét");
            A("Match case", "Phân biệt hoa thường");
            A("Measure", "Đo");
            A("Merge", "Ghép");
            A("More tools", "Thêm công cụ");
            A("New blank PDF (Ctrl+N)", "PDF trống mới (Ctrl+N)");
            A("Next match (Enter / F3)", "Kết quả tiếp (Enter / F3)");
            A("Next page", "Trang sau");
            A("No arrow", "Không mũi tên");
            A("Note", "Ghi chú");
            A("OCR", "OCR");
            A("Opacity", "Độ trong suốt");
            A("Open", "Mở");
            A("Open (Ctrl+O)", "Mở (Ctrl+O)");
            A("Open another file (Ctrl+O)", "Mở tệp khác (Ctrl+O)");
            A("Open file location", "Mở thư mục chứa tệp");
            A("Open in default app", "Mở bằng ứng dụng mặc định");
            A("Open the Merge window: move or copy pages between files, merge, split and save", "Mở cửa sổ Ghép: di chuyển hoặc sao chép trang giữa các tệp, ghép, tách và lưu");
            A("Organize", "Sắp xếp");
            A("Oval", "Ô-van");
            A("Overlay the drawings of two versions: red = only in the old one, blue = only in the new one", "Chồng bản vẽ của hai phiên bản: đỏ = chỉ có ở bản cũ, xanh = chỉ có ở bản mới");
            A("Page view", "Chế độ xem trang");
            A("Pencil", "Bút chì");
            A("Previous match (Shift+Enter / Shift+F3)", "Kết quả trước (Shift+Enter / Shift+F3)");
            A("Previous page", "Trang trước");
            A("Print", "In");
            A("Print (Ctrl+P)", "In (Ctrl+P)");
            A("Protect", "Bảo vệ");
            A("Put your signature or a stamp at the same place on many pages.", "Đặt chữ ký hoặc dấu ở cùng một vị trí trên nhiều trang.");
            A("Read the text of scanned pages (Vietnamese and Latin letters) into a searchable copy", "Đọc chữ của các trang quét (tiếng Việt và chữ Latin) thành một bản sao tìm kiếm được");
            A("Rect", "Chữ nhật");
            A("Rectangle", "Hình chữ nhật");
            A("Redo (Ctrl+Y)", "Làm lại (Ctrl+Y)");
            A("Reload", "Tải lại");
            A("Replace sheets from revision…", "Thay bản vẽ từ bản sửa đổi…");
            A("Replace the drawings of this file with the revised ones from another XT plot", "Thay các bản vẽ của tệp này bằng bản sửa đổi từ một lần plot XT khác");
            A("Rotate left", "Xoay trái");
            A("Rotate right", "Xoay phải");
            A("Rotate the page(s) 90° left — kept in the file when you save (Ctrl+S)", "Xoay trang 90° sang trái — được lưu vào tệp khi bạn lưu (Ctrl+S)");
            A("Rotate the page(s) 90° right — kept in the file when you save (Ctrl+S)", "Xoay trang 90° sang phải — được lưu vào tệp khi bạn lưu (Ctrl+S)");
            A("Rotate the view left (view only, the file is not changed)", "Xoay chế độ xem sang trái (chỉ xoay khi xem, tệp không đổi)");
            A("Rotate the view right (view only, the file is not changed)", "Xoay chế độ xem sang phải (chỉ xoay khi xem, tệp không đổi)");
            A("Rotate view", "Xoay chế độ xem");
            A("Save", "Lưu");
            A("Save (Ctrl+S)", "Lưu (Ctrl+S)");
            A("Save as…", "Lưu thành…");
            A("Save as… (Ctrl+Shift+S)", "Lưu thành… (Ctrl+Shift+S)");
            A("Search commands…   Ctrl+K", "Tìm lệnh…   Ctrl+K");
            A("Search commands, files and pages…   Ctrl+K", "Tìm lệnh, tệp và trang…   Ctrl+K");
            A("Select", "Chọn");
            A("Select a page to view", "Chọn một trang để xem");
            A("Settings", "Cài đặt");
            A("Shapes", "Hình vẽ");
            A("Show / hide the search options", "Hiện / ẩn tùy chọn tìm kiếm");
            A("Show document encryption and permissions", "Xem mã hóa và quyền của tài liệu");
            A("Single page", "Từng trang");
            A("Squiggly", "Lượn sóng");
            A("Squiggly underline", "Gạch chân lượn sóng");
            A("Squiggly underline: drag across text", "Gạch chân lượn sóng: kéo qua chữ");
            A("Stamp", "Dấu");
            A("Stamp Pages", "Đóng dấu trang");
            A("Start", "Bắt đầu");
            A("Start typing here…", "Bắt đầu gõ ở đây…");
            A("Sticky note: click the page, type, then Enter. Hover the icon to read it, click to edit.", "Ghi chú dán: bấm lên trang, gõ rồi Enter. Rê chuột lên biểu tượng để đọc, bấm để sửa.");
            A("Store", "Kho ảnh");
            A("Strike", "Gạch ngang");
            A("Strikethrough", "Gạch ngang");
            A("Strikethrough: drag across text", "Gạch ngang: kéo qua chữ");
            A("Text opacity", "Độ trong suốt của chữ");
            A("The Store of XT Capture: every capture is kept there", "Kho của XT Capture: mọi ảnh chụp đều được giữ ở đó");
            A("This document", "Tài liệu này");
            A("Tools", "Công cụ");
            A("Tools that do not fit the window width", "Các công cụ không vừa chiều rộng cửa sổ");
            A("Turn left", "Xoay trái");
            A("Turn right", "Xoay phải");
            A("Two-page view", "Xem hai trang");
            A("Type a page number, then press Enter", "Nhập số trang rồi nhấn Enter");
            A("Type text on the page: click where it goes, type, then Enter (Shift+Enter for a new line). Click existing text to edit.", "Gõ chữ lên trang: bấm vào vị trí cần đặt, gõ rồi Enter (Shift+Enter để xuống dòng). Bấm vào chữ có sẵn để sửa.");
            A("Typewriter", "Gõ chữ");
            A("Underline", "Gạch chân");
            A("Underline: drag across text", "Gạch chân: kéo qua chữ");
            A("Undo (Ctrl+Z)", "Hoàn tác (Ctrl+Z)");
            A("Unsaved changes (Ctrl+S to save)", "Có thay đổi chưa lưu (Ctrl+S để lưu)");
            A("Whole word", "Cả từ");
            A("Zoom in (+)", "Phóng to (+)");
            A("Zoom out (-)", "Thu nhỏ (-)");
            A("Search the whole file", "Tìm trong toàn bộ tệp");

            // ── Start page
            A("Capture any part of the screen into an editable PDF", "Chụp một vùng màn hình thành PDF chỉnh sửa được");
            A("Capture store", "Kho ảnh chụp");
            A("Capture the screen into an editable PDF", "Chụp màn hình thành PDF chỉnh sửa được");
            A("Choose pages and print settings", "Chọn trang và thiết lập in");
            A("Clear list", "Xóa danh sách");
            A("Combine files and arrange pages", "Ghép tệp và sắp xếp trang");
            A("Create a blank PDF (Ctrl+N)", "Tạo PDF trống (Ctrl+N)");
            A("Create a blank document", "Tạo tài liệu trống");
            A("Drop PDF files here", "Thả tệp PDF vào đây");
            A("Export or split the current document (Ctrl+Shift+E)", "Xuất hoặc tách tài liệu hiện tại (Ctrl+Shift+E)");
            A("Files you open will appear here.", "Các tệp bạn mở sẽ hiện ở đây.");
            A("Merge PDFs", "Ghép PDF");
            A("Merge files and organize pages", "Ghép tệp và sắp xếp trang");
            A("New PDF", "PDF mới");
            A("Open a PDF to split, export or print.", "Mở một PDF để tách, xuất hoặc in.");
            A("Open every PDF in a folder", "Mở mọi PDF trong một thư mục");
            A("Open file…  Ctrl+O", "Mở tệp…  Ctrl+O");
            A("Open folder…", "Mở thư mục…");
            A("Open the screen captures kept by XT Capture", "Mở các ảnh chụp màn hình do XT Capture giữ");
            A("Pin to the top", "Ghim lên đầu");
            A("Print PDF", "In PDF");
            A("Print the current document (Ctrl+P)", "In tài liệu hiện tại (Ctrl+P)");
            A("Quick locations", "Vị trí nhanh");
            A("Quick tools", "Công cụ nhanh");
            A("Recent", "Gần đây");
            A("Remove the files that are not pinned", "Xóa các tệp chưa được ghim");
            A("Save selected pages as new PDFs", "Lưu các trang đã chọn thành PDF mới");
            A("Screen capture", "Chụp màn hình");
            A("Split / Export", "Tách / Xuất");
            A("Your saved captures, ready to edit", "Các ảnh chụp đã lưu, sẵn sàng để chỉnh sửa");
            A("Enter run", "Enter để chạy");
            A("Esc close", "Esc để đóng");
            A("↑↓ navigate", "↑↓ để chọn");

            // ── side panel
            A("Add a bookmark for the page you're currently viewing", "Thêm dấu trang cho trang đang xem");
            A("Add bookmark", "Thêm dấu trang");
            A("Add bookmark here (current page)", "Thêm dấu trang tại đây (trang hiện tại)");
            A("Bookmarks", "Dấu trang");
            A("Comments", "Bình luận");
            A("Ctrl+C copy · Ctrl+V paste", "Ctrl+C sao chép · Ctrl+V dán");
            A("Cut", "Cắt");
            A("Delete the selected pages from this document (can be undone)", "Xóa các trang đã chọn khỏi tài liệu này (có thể hoàn tác)");
            A("Extract the selected pages to a new PDF", "Trích các trang đã chọn ra PDF mới");
            A("Extract…", "Trích xuất…");
            A("Hide the panel", "Ẩn bảng");
            A("History (who saved what)", "Lịch sử (ai đã lưu gì)");
            A("Insert pages from another PDF after the current page", "Chèn trang từ PDF khác sau trang hiện tại");
            A("Insert ▾", "Chèn ▾");
            A("Move", "Di chuyển");
            A("Move down", "Chuyển xuống");
            A("Move down one", "Chuyển xuống một bậc");
            A("Move to end", "Chuyển xuống cuối");
            A("Move to position…", "Chuyển đến vị trí…");
            A("Move to start", "Chuyển lên đầu");
            A("Move up", "Chuyển lên");
            A("Move up one", "Chuyển lên một bậc");
            A("OCR…", "OCR…");
            A("Pages", "Trang");
            A("Paper size of this page", "Khổ giấy của trang này");
            A("Paste after", "Dán vào sau");
            A("Paste before", "Dán vào trước");
            A("Read sheet info…", "Đọc thông tin bản vẽ…");
            A("Read sheet number, title and scale of these pages", "Đọc số hiệu, tên và tỉ lệ của các trang này");
            A("Read the text of scanned pages (kept until Ctrl+S)", "Đọc chữ của trang quét (giữ đến khi Ctrl+S)");
            A("Rename…", "Đổi tên…");
            A("Rotate the selected pages 90° left and save to the file", "Xoay các trang đã chọn 90° sang trái và lưu vào tệp");
            A("Rotate the selected pages 90° right and save to the file", "Xoay các trang đã chọn 90° sang phải và lưu vào tệp");
            A("Select pages of this size", "Chọn các trang cùng khổ");
            A("Sheets (drawings plotted by XT_PRINT / XT_SHEETS)", "Bản vẽ (plot bằng XT_PRINT / XT_SHEETS)");

            // ── find panel
            A("All open files", "Mọi tệp đang mở");
            A("Clear", "Xóa");
            A("Find in document…", "Tìm trong tài liệu…");
            A("Folder…", "Thư mục…");
            A("Make a searchable copy of this file", "Tạo bản sao tìm kiếm được của tệp này");
            A("Read the scanned pages (OCR)…", "Đọc các trang quét (OCR)…");
            A("Search every PDF in a folder (and its sub-folders), including files that are not open", "Tìm trong mọi PDF của một thư mục (và thư mục con), kể cả tệp chưa mở");
            A("This file", "Tệp này");

            // ── layers
            A("Add them to the layer list", "Thêm vào danh sách lớp");
            A("Back to the layer visibility saved in each file", "Về trạng thái hiện/ẩn lớp đã lưu trong từng tệp");
            A("Choose a saved layer view", "Chọn một chế độ xem lớp đã lưu");
            A("Expand / collapse all", "Mở rộng / thu gọn tất cả");
            A("Export PDF with this view…", "Xuất PDF với chế độ xem này…");
            A("Hide all", "Ẩn tất cả");
            A("Isolate selected", "Chỉ hiện lớp đã chọn");
            A("Layers with the same name from several files are merged into one. “N files” shows how many source files contain the layer.", "Các lớp cùng tên từ nhiều tệp được gộp thành một. “N tệp” cho biết có bao nhiêu tệp nguồn chứa lớp đó.");
            A("Manage…", "Quản lý…");
            A("Registers the missing layers in the file (appended update) so they can be hidden and shown", "Đăng ký các lớp còn thiếu vào tệp (ghi nối thêm) để có thể ẩn và hiện chúng");
            A("Rename and merge the layers of this file", "Đổi tên và gộp các lớp của tệp này");
            A("Reset", "Đặt lại");
            A("Save a copy of this document's pages with the current layer view as its default", "Lưu bản sao các trang của tài liệu này với chế độ xem lớp hiện tại làm mặc định");
            A("Save the current layers as a view", "Lưu các lớp hiện tại thành một chế độ xem");
            A("Search layers…", "Tìm lớp…");
            A("Show all", "Hiện tất cả");
            A("Show only the selected layer (and its sub-layers)", "Chỉ hiện lớp đã chọn (và các lớp con)");
            A("View", "Xem");

            // ── comments
            A("All types", "Mọi loại");
            A("Click to change the status", "Bấm để đổi trạng thái");
            A("Export list…", "Xuất danh sách…");
            A("Other", "Khác");
            A("Reply", "Trả lời");
            A("Save the comments shown (status, type and author filters apply) as a spreadsheet (CSV): sheet number, page, author, date, status, text", "Lưu các bình luận đang hiện (theo bộ lọc trạng thái, loại và tác giả) thành bảng tính (CSV): số hiệu bản vẽ, trang, tác giả, ngày, trạng thái, nội dung");
            A("Shape", "Hình");

            // ── stamp popup
            A("Add my name and today’s date", "Thêm tên tôi và ngày hôm nay");
            A("Click on the page to place · hold Shift to repeat · right-click a placed stamp to delete it", "Bấm lên trang để đặt · giữ Shift để đặt nhiều lần · bấm phải vào dấu đã đặt để xóa");
            A("Create your own stamp with New stamp…, or import a signature / seal image. Right-click a stamp to remove it.", "Tạo dấu riêng bằng “Dấu mới…”, hoặc nhập ảnh chữ ký / con dấu. Bấm phải vào dấu để xóa.");
            A("Import image…", "Nhập ảnh…");
            A("Mine", "Của tôi");
            A("New stamp…", "Dấu mới…");
            A("Stamps", "Dấu");
            A("Standard", "Chuẩn");

            // ── print
            A("All pages in range", "Mọi trang trong phạm vi");
            A("Auto (per page)", "Tự động (theo từng trang)");
            A("Auto-center", "Tự căn giữa");
            A("Black lines only", "Chỉ nét đen");
            A("Collate", "Sắp theo bộ");
            A("Copies:", "Số bản:");
            A("Custom scale", "Tỉ lệ tùy chọn");
            A("Document:", "Tài liệu:");
            A("Even pages only", "Chỉ trang chẵn");
            A("Everything darker than light gray prints black — crisp CAD lines, no gray fill", "Mọi thứ tối hơn xám nhạt đều in đen — nét CAD sắc, không có nền xám");
            A("Example: 1-12, 40, 55-60", "Ví dụ: 1-12, 40, 55-60");
            A("Fit to paper", "Vừa khổ giấy");
            A("High quality CAD (600 DPI)", "CAD chất lượng cao (600 DPI)");
            A("Landscape", "Ngang");
            A("Name:", "Tên:");
            A("None (actual size)", "Không (kích thước thật)");
            A("Odd pages only", "Chỉ trang lẻ");
            A("Open the printer driver's own settings (paper tray, quality, duplex, plotter options…)", "Mở thiết lập riêng của trình điều khiển máy in (khay giấy, chất lượng, in hai mặt, tùy chọn máy vẽ…)");
            A("Orientation", "Hướng giấy");
            A("Page sizes", "Khổ trang");
            A("Pages by size…", "Trang theo khổ…");
            A("Pages:", "Trang:");
            A("Paper", "Giấy");
            A("Paper:", "Giấy:");
            A("Portrait", "Dọc");
            A("Preview", "Xem trước");
            A("Print Handling", "Cách xử lý khi in");
            A("Print Range", "Phạm vi in");
            A("Print as grayscale", "In thang xám");
            A("Print by paper size…", "In theo khổ giấy…");
            A("Print the whole set: each paper size on its own printer and paper, from a saved profile (A1 on the plotter, A3 on the Canon…)", "In cả bộ: mỗi khổ giấy ra máy in và giấy riêng, theo hồ sơ đã lưu (A1 ra máy vẽ, A3 ra máy Canon…)");
            A("Properties…", "Thuộc tính…");
            A("Reading page sizes…", "Đang đọc khổ trang…");
            A("Reduce to paper (only larger pages)", "Thu nhỏ vừa giấy (chỉ trang lớn hơn)");
            A("Renders in memory-bounded bands for sharp CAD lines. Large sheets can take longer to spool.", "Kết xuất theo từng dải trong giới hạn bộ nhớ để nét CAD sắc. Bản vẽ lớn có thể mất thời gian hơn khi gửi in.");
            A("Reverse pages", "Đảo thứ tự trang");
            A("Select the pages of one paper size, or copy the size report", "Chọn các trang của một khổ giấy, hoặc sao chép báo cáo khổ giấy");
            A("Subset:", "Tập con:");
            A("Zoom:", "Phóng:");

            // ── export / save merged
            A("At each top-level bookmark", "Tại mỗi dấu trang cấp cao nhất");
            A("Browse…", "Duyệt…");
            A("By page ranges", "Theo phạm vi trang");
            A("By page size", "Theo cỡ trang");
            A("Cancel", "Hủy");
            A("Don’t split", "Không tách");
            A("Every N pages", "Mỗi N trang");
            A("Export", "Xuất");
            A("Export PDF", "Xuất PDF");
            A("File size", "Dung lượng tệp");
            A("Files that will be created", "Các tệp sẽ được tạo");
            A("Keep all layers", "Giữ mọi lớp");
            A("Layers", "Lớp");
            A("Only the layers of the current view, flattened", "Chỉ các lớp của chế độ xem hiện tại, đã làm phẳng");
            A("Optimized", "Tối ưu");
            A("Optimized rewrites the file with full compression. Drawings stay vector, images are not re-compressed.", "Tối ưu sẽ ghi lại tệp với nén tối đa. Bản vẽ vẫn là vector, ảnh không bị nén lại.");
            A("Original", "Gốc");
            A("Pages per file", "Số trang mỗi tệp");
            A("Save to", "Lưu vào");
            A("Separate the files with semicolons. “41-” means to the last page.", "Phân cách các tệp bằng dấu chấm phẩy. “41-” nghĩa là đến trang cuối.");
            A("Split into several files", "Tách thành nhiều tệp");
            A("Add a bookmark for each source file", "Thêm một dấu trang cho mỗi tệp nguồn");
            A("Add page numbers", "Thêm số trang");
            A("Bookmarks in the result", "Dấu trang trong kết quả");
            A("Change the names of the layers in the merged file", "Đổi tên các lớp trong tệp đã ghép");
            A("File name", "Tên tệp");
            A("Filter the layer list", "Lọc danh sách lớp");
            A("Keep bookmarks from the source files", "Giữ dấu trang từ các tệp nguồn");
            A("Keep each file’s layers separate", "Giữ lớp của từng tệp riêng biệt");
            A("Keep only the layers I choose", "Chỉ giữ các lớp tôi chọn");
            A("Merge same-name layers", "Gộp các lớp cùng tên");
            A("Optimize file size", "Tối ưu dung lượng tệp");
            A("Rename result layers…", "Đổi tên lớp kết quả…");
            A("Save merged file", "Lưu tệp đã ghép");
            A("The Layers panel of the result shows a tree: file, then that file’s layers", "Bảng Lớp của kết quả hiện dạng cây: tệp, rồi các lớp của tệp đó");
            A("The result will have no bookmarks.", "Kết quả sẽ không có dấu trang.");
            A("They are nested under the file’s bookmark.", "Chúng nằm dưới dấu trang của tệp.");
            A("Tick all", "Chọn tất cả");
            A("Ticked layers stay as their own layer (same names merge). All other layers become one layer called:", "Các lớp được tick giữ nguyên là lớp riêng (cùng tên thì gộp). Mọi lớp còn lại thành một lớp có tên:");

            // ── merge window
            A("Choose merge order", "Chọn thứ tự ghép");
            A("Choose the order of windows to merge", "Chọn thứ tự các cửa sổ cần ghép");
            A("Clean up", "Dọn dẹp");
            A("Columns: up to 3 windows side by side, the rest scroll sideways", "Cột: tối đa 3 cửa sổ cạnh nhau, phần còn lại cuộn ngang");
            A("Continue", "Tiếp tục");
            A("Drag", "Kéo");
            A("Drag = move · Ctrl+drag = copy", "Kéo = di chuyển · Ctrl+kéo = sao chép");
            A("Drag a row to place that window before another. Temp groups are not listed.", "Kéo một dòng để đặt cửa sổ đó lên trước cửa sổ khác. Nhóm tạm không được liệt kê.");
            A("Drag onto another window to insert all pages of this file (Ctrl = copy)", "Kéo vào cửa sổ khác để chèn mọi trang của tệp này (Ctrl = sao chép)");
            A("Export this draft window as a new PDF", "Xuất cửa sổ nháp này thành PDF mới");
            A("Export this temporary arrangement, in this order, as a new PDF. Original tabs are not changed.", "Xuất bố cục tạm này, theo thứ tự này, thành PDF mới. Các tab gốc không thay đổi.");
            A("Go to…", "Đi tới…");
            A("Inbox", "Hộp chờ");
            A("Layout", "Bố cục");
            A("Maximize / restore (double-click the title)", "Phóng to / khôi phục (nhấp đúp vào tiêu đề)");
            A("Merge into one file…", "Ghép thành một tệp…");
            A("Move printed PDFs that are no longer in the inbox or open anywhere to the Recycle Bin", "Chuyển các PDF đã in không còn trong hộp chờ hoặc không mở ở đâu vào Thùng rác");
            A("Move this window to the temporary shelf (excluded from Merge all)", "Chuyển cửa sổ này vào kệ tạm (không tính khi Ghép tất cả)");
            A("No files open", "Chưa mở tệp nào");
            A("Open PDF files to arrange and merge their pages here. This is a temporary draft.", "Mở các tệp PDF để sắp xếp và ghép trang tại đây. Đây là bản nháp tạm.");
            A("Open file…", "Mở tệp…");
            A("Page size", "Cỡ trang");
            A("Remove this window from the merge draft", "Bỏ cửa sổ này khỏi bản nháp ghép");
            A("Rows: one thumbnail row per window, up to 3 rows, the rest scroll down", "Hàng: mỗi cửa sổ một hàng ảnh thu nhỏ, tối đa 3 hàng, phần còn lại cuộn xuống");
            A("Show the window holding every printed / plotted PDF. Drag its pages into a merge window.", "Hiện cửa sổ chứa mọi PDF đã in / plot. Kéo các trang của nó vào cửa sổ ghép.");
            A("Switch to a window outside the current layout", "Chuyển sang cửa sổ ngoài bố cục hiện tại");
            A("Temp shelf", "Kệ tạm");
            A("Thumbnail size", "Cỡ ảnh thu nhỏ");
            A("Type a page number and press Enter", "Nhập số trang rồi nhấn Enter");
            A("Unsaved changes", "Có thay đổi chưa lưu");
            A("When saving the merged file, layers with the same name become one layer. Unticked: each file keeps its own layers, grouped by file", "Khi lưu tệp đã ghép, các lớp cùng tên thành một lớp. Bỏ tick: mỗi tệp giữ lớp riêng, nhóm theo tệp");

            // ── settings
            A("Accent color", "Màu nhấn");
            A("Appearance", "Giao diện");
            A("Applies the next time the app starts.", "Áp dụng ở lần mở ứng dụng tiếp theo.");
            A("Applies to files opened for the first time.", "Áp dụng cho các tệp mở lần đầu.");
            A("Back to the default folder under Local AppData", "Về thư mục mặc định trong Local AppData");
            A("Balance (default)", "Cân bằng (mặc định)");
            A("Clean up printed files older than (days)", "Dọn các tệp đã in cũ hơn (ngày)");
            A("Clear cache", "Xóa bộ đệm");
            A("Continuous scroll", "Cuộn liên tục");
            A("Dark", "Tối");
            A("Default", "Mặc định");
            A("Default view mode", "Chế độ xem mặc định");
            A("Display", "Hiển thị");
            A("File cache on disk", "Bộ đệm tệp trên đĩa");
            A("Files kept warm", "Số tệp giữ sẵn");
            A("Folder for printed files", "Thư mục chứa tệp đã in");
            A("Hand scrolls the page by dragging it; Select lets you drag across text right away, no need to switch tools first.", "Bàn tay cuộn trang bằng cách kéo; Chọn cho phép kéo qua chữ ngay, không cần đổi công cụ trước.");
            A("Integration", "Tích hợp");
            A("Language", "Ngôn ngữ");
            A("Choose the language of the whole interface.", "Chọn ngôn ngữ cho toàn bộ giao diện.");
            A("Color pages when printing", "Trang màu khi in");
            A("A page counts as a color page when at least this part of it is colored (a color picture, colored text or a colored table), so a small color logo in the title block does not make every sheet a color sheet.", "Một trang được tính là trang màu khi ít nhất phần này của trang có màu (ảnh màu, chữ màu hoặc bảng màu), để logo màu nhỏ ở khung tên không biến mọi bản vẽ thành trang màu.");
            A("0.2% of the page", "0,2% trang");
            A("0.5% of the page", "0,5% trang");
            A("1% of the page (default)", "1% trang (mặc định)");
            A("2% of the page", "2% trang");
            A("5% of the page", "5% trang");
            A("Line darkness", "Độ đậm nét vẽ");
            A("Draws thin lines of drawings darker so they stay easy to read. Applies the next time the app starts.", "Vẽ các nét mảnh của bản vẽ đậm hơn để dễ nhìn. Áp dụng ở lần mở ứng dụng tiếp theo.");
            A("As in the file", "Như trong tệp");
            A("Darker (default)", "Đậm hơn (mặc định)");
            A("Darkest", "Đậm nhất");
            A("Light", "Sáng");
            A("Light is the default. Dark is easier on the eyes for drawings with dark backgrounds. System follows Windows.", "Sáng là mặc định. Tối dễ nhìn hơn với bản vẽ nền tối. Hệ thống theo Windows.");
            A("Maximum performance", "Hiệu năng tối đa");
            A("Memory saving", "Tiết kiệm bộ nhớ");
            A("Open PDF files with this app", "Mở tệp PDF bằng ứng dụng này");
            A("Opens Windows Settings, where you choose PDF Reader Pro for .pdf files", "Mở Cài đặt Windows để bạn chọn PDF Reader Pro cho tệp .pdf");
            A("Performance & memory", "Hiệu năng & bộ nhớ");
            A("Print inbox > Clean up only offers printed PDFs that are no longer in the inbox or open and are at least this old, and asks before moving them to the Recycle Bin. 0 = any age.", "Hộp chờ in > Dọn dẹp chỉ đề xuất các PDF đã in không còn trong hộp chờ hoặc không mở và cũ ít nhất từng đó ngày, và hỏi trước khi chuyển vào Thùng rác. 0 = mọi tuổi.");
            A("Reader performance", "Hiệu năng trình đọc");
            A("Recently used files keep their memory for fast scrolling and zoom. Older files are released; reopening stays fast thanks to the disk cache.", "Các tệp dùng gần đây giữ bộ nhớ để cuộn và phóng nhanh. Tệp cũ hơn được giải phóng; mở lại vẫn nhanh nhờ bộ đệm trên đĩa.");
            A("Release the cached copies of files that are not on screen. They are read again when needed.", "Giải phóng bản lưu đệm của các tệp không hiện trên màn hình. Chúng sẽ được đọc lại khi cần.");
            A("Set as default…", "Đặt làm mặc định…");
            A("Show when someone else has the same file open", "Báo khi người khác đang mở cùng tệp");
            A("System", "Hệ thống");
            A("Theme", "Chủ đề");
            A("Tool when opening a file", "Công cụ khi mở tệp");
            A("Use this app when “View PDF” is pressed in pdfFactory", "Dùng ứng dụng này khi bấm “View PDF” trong pdfFactory");
            A("Used for the main button, the selected item and the drop marker.", "Dùng cho nút chính, mục đang chọn và dấu thả.");
            A("Writes a small hidden marker file next to each open PDF (removed when you close it), so other people using this app on the same folder, including a network share, are told.", "Ghi một tệp đánh dấu nhỏ ẩn cạnh mỗi PDF đang mở (xóa khi bạn đóng), để người khác dùng ứng dụng này trên cùng thư mục, kể cả thư mục mạng, được báo.");
            A("Zoom when opening a file", "Mức phóng khi mở tệp");

            // ── splash and the rest
            A("Starting…", "Đang khởi động…");
            A("Opening the document…", "Đang mở tài liệu…");
            A("Almost ready…", "Sắp xong…");
            A("XT Solution © 2026", "XT Solution © 2026");
        }
    }
}
